export enum IndicatorCategory {
  CALIDAD = 'CALIDAD',
  OPERACIONES = 'OPERACIONES',
  PRODUCTIVIDAD = 'PRODUCTIVIDAD',
  FINANCIERO = 'FINANCIERO',
  RECURSOS_HUMANOS = 'RECURSOS_HUMANOS',
  SEGURIDAD = 'SEGURIDAD',
  MEDIO_AMBIENTE = 'MEDIO_AMBIENTE',
  SATISFACCION_CLIENTE = 'SATISFACCION_CLIENTE'
}

export enum IndicatorType {
  PORCENTAJE = 'PORCENTAJE',
  TIEMPO = 'TIEMPO',
  NUMERICO = 'NUMERICO',
  MONETARIO = 'MONETARIO',
  RATIO = 'RATIO',
  INDICE = 'INDICE'
}

export enum IndicatorTrend {
  UP = 'UP',
  DOWN = 'DOWN',
  STABLE = 'STABLE'
}

export enum IndicatorStatus {
  GOOD = 'GOOD',
  WARNING = 'WARNING',
  CRITICAL = 'CRITICAL'
}

export enum IndicatorFrequency {
  DIARIO = 'DIARIO',
  SEMANAL = 'SEMANAL',
  MENSUAL = 'MENSUAL',
  TRIMESTRAL = 'TRIMESTRAL',
  SEMESTRAL = 'SEMESTRAL',
  ANUAL = 'ANUAL'
}
